Repository reading-log/backend, pull requests merged in 2024-03, with the labels that each got.

#3 프로젝트 설정
  .gitignore
  src/main/java/com/api/readinglog/common/security/SecurityConfig.java
  src/main/resources/application.properties
  src/main/resources/application.yml
Labels: documentation, feature

#5 Feature/#4 회원 엔티티 구현
  src/main/java/com/api/readinglog/common/base/BaseTimeConfig.java
  src/main/java/com/api/readinglog/common/base/BaseTimeEntity.java
  src/main/java/com/api/readinglog/common/security/SecurityConfig.java
  src/main/java/com/api/readinglog/domain/entity/Member.java
  src/main/java/com/api/readinglog/domain/entity/MemberRole.java
  src/main/java/com/api/readinglog/domain/repository/MemberRepository.java
  src/test/java/com/api/readinglog/domain/entity/MemberTest.java
Labels: pull request, feature, test

#9 Feature/#6 - API 공통 응답 포맷 구현
  src/main/java/com/api/readinglog/common/response/Response.java
  src/main/java/com/api/readinglog/domain/member/controller/MemberController.java
  src/main/java/com/api/readinglog/domain/member/entity/Member.java
  src/main/java/com/api/readinglog/domain/member/entity/MemberRole.java
  src/main/java/com/api/readinglog/domain/member/repository/MemberRepository.java
  src/test/java/com/api/readinglog/domain/entity/MemberTest.java
Labels: pull request, feature

#10 Feature/#7 - 예외 핸들러 구현
  src/main/java/com/api/readinglog/common/exception/CustomException.java
  src/main/java/com/api/readinglog/common/exception/ErrorCode.java
  src/main/java/com/api/readinglog/common/exception/GlobalExceptionAdvice.java
  src/main/java/com/api/readinglog/common/exception/custom/MemberException.java
  src/main/java/com/api/readinglog/common/response/Response.java
  src/main/java/com/api/readinglog/domain/member/controller/MemberController.java
Labels: pull request, feature

#13 회원 가입 기능 구현
  src/main/java/com/api/readinglog/common/security/SecurityConfig.java
  src/main/java/com/api/readinglog/domain/member/controller/MemberController.java
  src/main/java/com/api/readinglog/domain/member/controller/dto/JoinRequest.java
  src/main/java/com/api/readinglog/domain/member/entity/Member.java
  src/main/java/com/api/readinglog/domain/member/repository/MemberRepository.java
  src/main/java/com/api/readinglog/domain/member/service/MemberService.java
Labels: pull request, feature

#14 로그인 기능 구현
  build.gradle
  src/main/java/com/api/readinglog/common/jwt/JwtAuthenticationFilter.java
  src/main/java/com/api/readinglog/common/jwt/JwtToken.java
  src/main/java/com/api/readinglog/common/jwt/JwtTokenProvider.java
  src/main/java/com/api/readinglog/common/security/CustomUserDetailsService.java
  src/main/java/com/api/readinglog/common/security/SecurityConfig.java
  src/main/java/com/api/readinglog/domain/member/controller/MemberController.java
  src/main/java/com/api/readinglog/domain/member/controller/dto/JoinRequest.java
  src/main/java/com/api/readinglog/domain/member/controller/dto/LoginRequest.java
  src/main/java/com/api/readinglog/domain/member/controller/dto/LoginResponse.java
  src/main/java/com/api/readinglog/domain/member/entity/Member.java
  src/main/java/com/api/readinglog/domain/member/service/MemberService.java
Labels: pull request, feature

#20 회원가입, 로그인 기능 리팩토링
  src/main/java/com/api/readinglog/common/oauth/CustomOAuth2UserService.java
  src/main/java/com/api/readinglog/common/oauth/OAuthSuccessHandler.java
  src/main/java/com/api/readinglog/common/security/CustomUserDetailsService.java
  src/main/java/com/api/readinglog/domain/member/controller/MemberController.java
  src/main/java/com/api/readinglog/domain/member/entity/Member.java
  src/main/java/com/api/readinglog/domain/member/entity/MemberRole.java
  src/main/java/com/api/readinglog/domain/member/repository/MemberRepository.java
  src/main/java/com/api/readinglog/domain/member/service/MemberService.java
  src/test/java/com/api/readinglog/domain/entity/MemberTest.java
Labels: pull request, refactor

#24 책 검색 기능 구현
  build.gradle
  src/main/java/com/api/readinglog/common/exception/ErrorCode.java
  src/main/java/com/api/readinglog/common/exception/custom/BookException.java
  src/main/java/com/api/readinglog/common/webclient/WebClientConfig.java
  src/main/java/com/api/readinglog/domain/book/controller/BookController.java
  src/main/java/com/api/readinglog/domain/book/dto/BookSearchApiResponse.java
  src/main/java/com/api/readinglog/domain/book/entity/Book.java
  src/main/java/com/api/readinglog/domain/book/repository/BookRepository.java
  src/main/java/com/api/readinglog/domain/book/service/BookService.java
Labels: pull request, feature

#28 회원가입 기능 추가
  build.gradle
  src/main/java/com/api/readinglog/common/aws/AmazonS3Config.java
  src/main/java/com/api/readinglog/common/aws/AmazonS3Service.java
  src/main/java/com/api/readinglog/common/exception/ErrorCode.java
  src/main/java/com/api/readinglog/common/exception/GlobalExceptionAdvice.java
  src/main/java/com/api/readinglog/common/exception/custom/AwsS3Exception.java
  src/main/java/com/api/readinglog/common/response/Response.java
  src/main/java/com/api/readinglog/domain/member/controller/MemberController.java
  src/main/java/com/api/readinglog/domain/member/controller/dto/JoinRequest.java
  src/main/java/com/api/readinglog/domain/member/entity/Member.java
  src/main/java/com/api/readinglog/domain/member/repository/MemberRepository.java
  src/main/java/com/api/readinglog/domain/member/service/MemberService.java
Labels: pull request, feature

#29 책 등록 기능 구현
  src/main/java/com/api/readinglog/domain/book/controller/BookController.java
  src/main/java/com/api/readinglog/domain/book/dto/BookDirectRequest.java
  src/main/java/com/api/readinglog/domain/book/dto/BookRegisterRequest.java
  src/main/java/com/api/readinglog/domain/book/entity/Book.java
  src/main/java/com/api/readinglog/domain/book/service/BookService.java
  src/main/java/com/api/readinglog/domain/member/service/MemberService.java
  src/main/resources/data.sql
Labels: pull request, feature

#31 CustomUserDetail 리팩토링
  src/main/java/com/api/readinglog/common/oauth/CustomOAuth2UserService.java
  src/main/java/com/api/readinglog/common/oauth/OAuthSuccessHandler.java
  src/main/java/com/api/readinglog/common/security/CustomUserDetail.java
  src/main/java/com/api/readinglog/domain/member/entity/Member.java
  src/main/java/com/api/readinglog/domain/member/service/MemberService.java
Labels: pull request, feature

#33 OAuthSuccessHandler 수정
  src/main/java/com/api/readinglog/common/jwt/JwtTokenProvider.java
  src/main/java/com/api/readinglog/common/oauth/OAuthSuccessHandler.java
  src/main/java/com/api/readinglog/common/security/CustomUserDetailsService.java
  src/main/java/com/api/readinglog/common/webclient/WebClientConfig.java
  src/main/java/com/api/readinglog/domain/book/controller/BookController.java
Labels: pull request, feature

#36 책 삭제 기능 구현
  src/main/java/com/api/readinglog/common/exception/ErrorCode.java
  src/main/java/com/api/readinglog/domain/book/controller/BookController.java
  src/main/java/com/api/readinglog/domain/book/service/BookService.java
Labels: pull request, feature

#37 마이페이지 기능 구현
  src/main/java/com/api/readinglog/common/aws/AmazonS3Service.java
  src/main/java/com/api/readinglog/common/exception/ErrorCode.java
  src/main/java/com/api/readinglog/common/oauth/CustomOAuth2UserService.java
  src/main/java/com/api/readinglog/common/oauth/OAuth2Attribute.java
  src/main/java/com/api/readinglog/common/oauth/OAuth2RevokeService.java
  src/main/java/com/api/readinglog/common/oauth/OAuthSuccessHandler.java
  src/main/java/com/api/readinglog/domain/member/controller/MemberController.java
  src/main/java/com/api/readinglog/domain/member/controller/dto/request/DeleteRequest.java
  src/main/java/com/api/readinglog/domain/member/controller/dto/request/JoinRequest.java
  src/main/java/com/api/readinglog/domain/member/controller/dto/request/LoginRequest.java
  src/main/java/com/api/readinglog/domain/member/controller/dto/request/UpdateProfileRequest.java
  src/main/java/com/api/readinglog/domain/member/controller/dto/response/LoginResponse.java
  src/main/java/com/api/readinglog/domain/member/controller/dto/response/MemberDetailsResponse.java
  src/main/java/com/api/readinglog/domain/member/entity/Member.java
  src/main/java/com/api/readinglog/domain/member/service/MemberService.java
  src/main/java/com/api/readinglog/domain/token/entity/AccessToken.java
  src/main/java/com/api/readinglog/domain/token/repository/AccessTokenRepository.java
Labels: pull request, feature

#38 배포 테스트를 위한 develop 브랜치 병합
  .github/pull_request_template.md
  .github/workflow/work.yml
  .gitignore
  Dockerfile
  README.md
  build.gradle
  src/main/java/com/api/readinglog/common/aws/AmazonS3Config.java
  src/main/java/com/api/readinglog/common/aws/AmazonS3Service.java
  src/main/java/com/api/readinglog/common/base/BaseTimeConfig.java
  src/main/java/com/api/readinglog/common/base/BaseTimeEntity.java
  src/main/java/com/api/readinglog/common/exception/CustomException.java
  src/main/java/com/api/readinglog/common/exception/ErrorCode.java
  src/main/java/com/api/readinglog/common/exception/GlobalExceptionAdvice.java
  src/main/java/com/api/readinglog/common/exception/custom/AwsS3Exception.java
  src/main/java/com/api/readinglog/common/exception/custom/BookException.java
  src/main/java/com/api/readinglog/common/exception/custom/MemberException.java
  src/main/java/com/api/readinglog/common/jwt/JwtAuthenticationFilter.java
  src/main/java/com/api/readinglog/common/jwt/JwtToken.java
  src/main/java/com/api/readinglog/common/jwt/JwtTokenProvider.java
  src/main/java/com/api/readinglog/common/oauth/CustomOAuth2UserService.java
  src/main/java/com/api/readinglog/common/oauth/OAuth2Attribute.java
  src/main/java/com/api/readinglog/common/oauth/OAuth2RevokeService.java
  src/main/java/com/api/readinglog/common/oauth/OAuthSuccessHandler.java
  src/main/java/com/api/readinglog/common/response/Response.java
  src/main/java/com/api/readinglog/common/security/CustomUserDetail.java
  src/main/java/com/api/readinglog/common/security/CustomUserDetailsService.java
  src/main/java/com/api/readinglog/common/security/SecurityConfig.java
  src/main/java/com/api/readinglog/common/webclient/WebClientConfig.java
  src/main/java/com/api/readinglog/domain/book/controller/BookController.java
  src/main/java/com/api/readinglog/domain/book/dto/BookDirectRequest.java
  src/main/java/com/api/readinglog/domain/book/dto/BookRegisterRequest.java
  src/main/java/com/api/readinglog/domain/book/dto/BookSearchApiResponse.java
  src/main/java/com/api/readinglog/domain/book/entity/Book.java
  src/main/java/com/api/readinglog/domain/book/repository/BookRepository.java
  src/main/java/com/api/readinglog/domain/book/service/BookService.java
  src/main/java/com/api/readinglog/domain/member/controller/MemberController.java
  src/main/java/com/api/readinglog/domain/member/controller/dto/request/DeleteRequest.java
  src/main/java/com/api/readinglog/domain/member/controller/dto/request/JoinRequest.java
  src/main/java/com/api/readinglog/domain/member/controller/dto/request/LoginRequest.java
  src/main/java/com/api/readinglog/domain/member/controller/dto/request/UpdateProfileRequest.java
  src/main/java/com/api/readinglog/domain/member/controller/dto/response/LoginResponse.java
  src/main/java/com/api/readinglog/domain/member/controller/dto/response/MemberDetailsResponse.java
  src/main/java/com/api/readinglog/domain/member/entity/Member.java
  src/main/java/com/api/readinglog/domain/member/entity/MemberRole.java
  src/main/java/com/api/readinglog/domain/member/repository/MemberRepository.java
  src/main/java/com/api/readinglog/domain/member/service/MemberService.java
  src/main/java/com/api/readinglog/domain/token/entity/AccessToken.java
  src/main/java/com/api/readinglog/domain/token/repository/AccessTokenRepository.java
  src/main/resources/application.properties
  src/main/resources/application.yml
  src/main/resources/data.sql
  src/test/java/com/api/readinglog/domain/entity/MemberTest.java
Labels: pull request, deploy

#39 work.yml 디렉토리 수정
  .github/workflows/work.yml
Labels: pull request, deploy

#40 main 변경점 develop 브랜치에 병합
  .github/workflows/work.yml
  README.md
  build.gradle
  src/main/java/com/api/readinglog/common/web/WebConfig.java
  src/main/resources/application.yml
  src/test/java/com/api/readinglog/ReadinglogApplicationTests.java
  src/test/java/com/api/readinglog/domain/entity/MemberTest.java
Labels: pull request, deploy, feature

#42 cors 설정 변경
  src/main/java/com/api/readinglog/common/web/WebConfig.java
Labels: pull request, feature

#43 ci cd 테스트
  src/main/java/com/api/readinglog/common/web/WebConfig.java
Labels: pull request, deploy, feature

#46 토큰 값 쿠키에 저장
  src/main/java/com/api/readinglog/common/oauth/OAuthSuccessHandler.java
  src/main/java/com/api/readinglog/common/security/util/CookieUtils.java
  src/main/java/com/api/readinglog/common/web/WebConfig.java
  src/main/java/com/api/readinglog/domain/member/controller/MemberController.java
Labels: feature

#47 쿠키에 토큰 값 저장 테스트
  src/main/java/com/api/readinglog/common/oauth/OAuthSuccessHandler.java
  src/main/java/com/api/readinglog/common/security/util/CookieUtils.java
  src/main/java/com/api/readinglog/common/web/WebConfig.java
  src/main/java/com/api/readinglog/domain/member/controller/MemberController.java
Labels: feature

#52 토큰 재발급 기능 구현
  src/main/java/com/api/readinglog/common/exception/ErrorCode.java
  src/main/java/com/api/readinglog/common/exception/custom/JwtException.java
  src/main/java/com/api/readinglog/common/jwt/JwtAuthenticationFilter.java
  src/main/java/com/api/readinglog/common/jwt/JwtTokenProvider.java
  src/main/java/com/api/readinglog/common/oauth/CustomOAuth2UserService.java
  src/main/java/com/api/readinglog/common/oauth/OAuthSuccessHandler.java
  src/main/java/com/api/readinglog/domain/member/controller/MemberController.java
  src/main/java/com/api/readinglog/domain/member/service/MemberService.java
  src/main/java/com/api/readinglog/domain/token/entity/RefreshToken.java
  src/main/java/com/api/readinglog/domain/token/entity/SocialAccessToken.java
  src/main/java/com/api/readinglog/domain/token/repository/AccessTokenRepository.java
  src/main/java/com/api/readinglog/domain/token/repository/RefreshTokenRepository.java
  src/main/java/com/api/readinglog/domain/token/repository/SocialAccessTokenRepository.java
  src/test/java/com/api/readinglog/domain/member/service/MemberTokenReissueTest.java
Labels: pull request, feature, test

#56 로그아웃 API 구현
  src/main/java/com/api/readinglog/common/security/util/JwtUtils.java
  src/main/java/com/api/readinglog/domain/member/controller/MemberController.java
  src/main/java/com/api/readinglog/domain/member/service/MemberService.java
  src/main/java/com/api/readinglog/domain/token/repository/RefreshTokenRepository.java
Labels: pull request, feature

#57 하이라이트 API 구현
  src/main/java/com/api/readinglog/common/exception/ErrorCode.java
  src/main/java/com/api/readinglog/common/exception/custom/HighlightException.java
  src/main/java/com/api/readinglog/domain/book/service/BookService.java
  src/main/java/com/api/readinglog/domain/hightlight/controller/HighlightController.java
  src/main/java/com/api/readinglog/domain/hightlight/controller/dto/request/ModifyRequest.java
  src/main/java/com/api/readinglog/domain/hightlight/controller/dto/request/WriteRequest.java
  src/main/java/com/api/readinglog/domain/hightlight/controller/dto/response/HighlightResponse.java
  src/main/java/com/api/readinglog/domain/hightlight/entity/Highlight.java
  src/main/java/com/api/readinglog/domain/hightlight/repository/HighlightRepository.java
  src/main/java/com/api/readinglog/domain/hightlight/service/HighlightService.java
Labels: pull request, feature

#58 한 줄 리뷰 API 구현
  src/main/java/com/api/readinglog/common/exception/ErrorCode.java
  src/main/java/com/api/readinglog/common/exception/custom/SummaryException.java
  src/main/java/com/api/readinglog/domain/hightlight/controller/HighlightController.java
  src/main/java/com/api/readinglog/domain/hightlight/service/HighlightService.java
  src/main/java/com/api/readinglog/domain/summary/controller/SummaryController.java
  src/main/java/com/api/readinglog/domain/summary/controller/dto/request/ModifyRequest.java
  src/main/java/com/api/readinglog/domain/summary/controller/dto/request/WriteRequest.java
  src/main/java/com/api/readinglog/domain/summary/controller/dto/response/MySummaryResponse.java
  src/main/java/com/api/readinglog/domain/summary/controller/dto/response/SummaryResponse.java
  src/main/java/com/api/readinglog/domain/summary/entity/Summary.java
  src/main/java/com/api/readinglog/domain/summary/repository/SummaryRepository.java
  src/main/java/com/api/readinglog/domain/summary/service/SummaryService.java
Labels: pull request, feature

#59 서평 API 구현
  src/main/java/com/api/readinglog/common/exception/ErrorCode.java
  src/main/java/com/api/readinglog/common/exception/custom/ReviewException.java
  src/main/java/com/api/readinglog/domain/review/controller/ReviewController.java
  src/main/java/com/api/readinglog/domain/review/controller/dto/request/ModifyRequest.java
  src/main/java/com/api/readinglog/domain/review/controller/dto/request/WriteRequest.java
  src/main/java/com/api/readinglog/domain/review/controller/dto/response/ReviewResponse.java
  src/main/java/com/api/readinglog/domain/review/entity/Review.java
  src/main/java/com/api/readinglog/domain/review/repository/ReviewRepository.java
  src/main/java/com/api/readinglog/domain/review/service/ReviewService.java
Labels: pull request, feature

#61 테스트 코드 주석 처리
  src/main/java/com/api/readinglog/common/oauth/CustomOAuth2UserService.java
  src/test/java/com/api/readinglog/ReadinglogApplicationTests.java
  src/test/java/com/api/readinglog/domain/member/service/MemberTokenReissueTest.java
Labels: pull request, test

#64 회원 도메인 기능 추가
  build.gradle
  src/main/java/com/api/readinglog/common/exception/ErrorCode.java
  src/main/java/com/api/readinglog/common/exception/custom/EmailException.java
  src/main/java/com/api/readinglog/domain/email/config/EmailConfig.java
  src/main/java/com/api/readinglog/domain/email/config/SchedulerConfig.java
  src/main/java/com/api/readinglog/domain/email/dto/AuthCodeVerificationRequest.java
  src/main/java/com/api/readinglog/domain/email/dto/EmailRequest.java
  src/main/java/com/api/readinglog/domain/email/entity/EmailAuth.java
  src/main/java/com/api/readinglog/domain/email/repository/EmailAuthRepository.java
  src/main/java/com/api/readinglog/domain/email/service/EmailService.java
  src/main/java/com/api/readinglog/domain/member/controller/MemberController.java
  src/main/java/com/api/readinglog/domain/member/controller/dto/request/JoinNicknameRequest.java
  src/main/java/com/api/readinglog/domain/member/controller/dto/request/UpdatePasswordRequest.java
  src/main/java/com/api/readinglog/domain/member/entity/Member.java
  src/main/java/com/api/readinglog/domain/member/service/MemberService.java
  src/main/resources/templates/authCode.html
  src/main/resources/templates/tempPassword.html
Labels: pull request, feature

#67 회원 도메인 리팩토링
  build.gradle
  src/main/java/com/api/readinglog/common/aws/AmazonS3Service.java
  src/main/java/com/api/readinglog/common/exception/ErrorCode.java
  src/main/java/com/api/readinglog/common/redis/config/RedisConfig.java
  src/main/java/com/api/readinglog/common/redis/service/RedisService.java
  src/main/java/com/api/readinglog/common/security/util/CookieUtils.java
  src/main/java/com/api/readinglog/domain/email/config/SchedulerConfig.java
  src/main/java/com/api/readinglog/domain/email/entity/EmailAuth.java
  src/main/java/com/api/readinglog/domain/email/repository/EmailAuthRepository.java
  src/main/java/com/api/readinglog/domain/email/service/EmailService.java
  src/main/java/com/api/readinglog/domain/member/controller/MemberController.java
  src/main/java/com/api/readinglog/domain/member/service/MemberService.java
Labels: pull request, feature, refactor

#68 책 API 리팩토링
  src/main/java/com/api/readinglog/common/aws/AmazonS3Service.java
  src/main/java/com/api/readinglog/common/aws/DomainType.java
  src/main/java/com/api/readinglog/common/image/ImageUtil.java
  src/main/java/com/api/readinglog/domain/book/dto/BookSearchApiResponse.java
  src/main/java/com/api/readinglog/domain/book/service/BookService.java
  src/main/java/com/api/readinglog/domain/member/service/MemberService.java
  src/main/resources/data.sql
Labels: pull request, feature, refactor

#70 오타 수정
  src/main/java/com/api/readinglog/domain/member/service/MemberService.java
Labels: bug, pull request
