Repository reading-log/backend, pull requests merged in 2024-04, with the labels that each got.

#74 독서 날짜 기록 기능 구현
  src/main/java/com/api/readinglog/common/exception/ErrorCode.java
  src/main/java/com/api/readinglog/common/exception/custom/RecordException.java
  src/main/java/com/api/readinglog/domain/record/controller/RecordController.java
  src/main/java/com/api/readinglog/domain/record/controller/dto/request/RecordModifyRequest.java
  src/main/java/com/api/readinglog/domain/record/controller/dto/request/RecordWriteRequest.java
  src/main/java/com/api/readinglog/domain/record/controller/dto/response/RecordResponse.java
  src/main/java/com/api/readinglog/domain/record/entity/Record.java
  src/main/java/com/api/readinglog/domain/record/repository/RecordRepository.java
  src/main/java/com/api/readinglog/domain/record/service/RecordService.java
  src/main/resources/data.sql
Labels: pull request, feature

#75 책 삭제 기능 수정
  src/main/java/com/api/readinglog/domain/book/entity/Book.java
  src/main/java/com/api/readinglog/domain/hightlight/service/HighlightService.java
  src/main/java/com/api/readinglog/domain/record/service/RecordService.java
  src/main/java/com/api/readinglog/domain/review/service/ReviewService.java
  src/main/java/com/api/readinglog/domain/summary/service/SummaryService.java
Labels: pull request, feature

#76 북로그 기능 구현
  src/main/java/com/api/readinglog/common/exception/ErrorCode.java
  src/main/java/com/api/readinglog/domain/book/entity/Book.java
  src/main/java/com/api/readinglog/domain/booklog/controller/BookLogController.java
  src/main/java/com/api/readinglog/domain/booklog/controller/dto/BookLogResponse.java
  src/main/java/com/api/readinglog/domain/booklog/service/BookLogService.java
  src/main/java/com/api/readinglog/domain/highlight/controller/HighlightController.java
  src/main/java/com/api/readinglog/domain/highlight/controller/dto/request/ModifyRequest.java
  src/main/java/com/api/readinglog/domain/highlight/controller/dto/request/WriteRequest.java
  src/main/java/com/api/readinglog/domain/highlight/controller/dto/response/HighlightResponse.java
  src/main/java/com/api/readinglog/domain/highlight/entity/Highlight.java
  src/main/java/com/api/readinglog/domain/highlight/repository/HighlightRepository.java
  src/main/java/com/api/readinglog/domain/highlight/service/HighlightService.java
  src/main/java/com/api/readinglog/domain/hightlight/repository/HighlightRepository.java
  src/main/java/com/api/readinglog/domain/review/controller/ReviewController.java
  src/main/java/com/api/readinglog/domain/review/repository/ReviewRepository.java
  src/main/java/com/api/readinglog/domain/review/service/ReviewService.java
  src/main/java/com/api/readinglog/domain/summary/controller/SummaryController.java
  src/main/java/com/api/readinglog/domain/summary/service/SummaryService.java
Labels: pull request, feature, refactor

#79 스웨거 설정 추가
  src/main/java/com/api/readinglog/common/swagger/SwaggerConfig.java
  src/main/java/com/api/readinglog/domain/book/controller/BookController.java
  src/main/java/com/api/readinglog/domain/highlight/controller/HighlightController.java
  src/main/java/com/api/readinglog/domain/member/controller/MemberController.java
  src/main/java/com/api/readinglog/domain/record/controller/RecordController.java
  src/main/java/com/api/readinglog/domain/review/controller/ReviewController.java
  src/main/java/com/api/readinglog/domain/summary/controller/SummaryController.java
Labels: documentation, pull request, feature

#80 회원, 북로그 도메인 Swagger API 문서화
  build.gradle
  src/main/java/com/api/readinglog/domain/booklog/controller/BookLogController.java
  src/main/java/com/api/readinglog/domain/email/dto/AuthCodeVerificationRequest.java
  src/main/java/com/api/readinglog/domain/email/dto/EmailRequest.java
  src/main/java/com/api/readinglog/domain/member/controller/MemberController.java
  src/main/java/com/api/readinglog/domain/member/controller/dto/request/DeleteRequest.java
  src/main/java/com/api/readinglog/domain/member/controller/dto/request/LoginRequest.java
  src/main/java/com/api/readinglog/domain/member/controller/dto/request/UpdatePasswordRequest.java
Labels: documentation, pull request, feature

#81 04.03 Main merge
  build.gradle
  src/main/java/com/api/readinglog/common/aws/AmazonS3Service.java
  src/main/java/com/api/readinglog/common/aws/DomainType.java
  src/main/java/com/api/readinglog/common/exception/ErrorCode.java
  src/main/java/com/api/readinglog/common/exception/custom/EmailException.java
  src/main/java/com/api/readinglog/common/exception/custom/RecordException.java
  src/main/java/com/api/readinglog/common/image/ImageUtil.java
  src/main/java/com/api/readinglog/common/redis/config/RedisConfig.java
  src/main/java/com/api/readinglog/common/redis/service/RedisService.java
  src/main/java/com/api/readinglog/common/security/util/CookieUtils.java
  src/main/java/com/api/readinglog/common/swagger/SwaggerConfig.java
  src/main/java/com/api/readinglog/domain/book/controller/BookController.java
  src/main/java/com/api/readinglog/domain/book/dto/BookSearchApiResponse.java
  src/main/java/com/api/readinglog/domain/book/entity/Book.java
  src/main/java/com/api/readinglog/domain/book/service/BookService.java
  src/main/java/com/api/readinglog/domain/booklog/controller/BookLogController.java
  src/main/java/com/api/readinglog/domain/booklog/controller/dto/BookLogResponse.java
  src/main/java/com/api/readinglog/domain/booklog/service/BookLogService.java
  src/main/java/com/api/readinglog/domain/email/config/EmailConfig.java
  src/main/java/com/api/readinglog/domain/email/dto/AuthCodeVerificationRequest.java
  src/main/java/com/api/readinglog/domain/email/dto/EmailRequest.java
  src/main/java/com/api/readinglog/domain/email/service/EmailService.java
  src/main/java/com/api/readinglog/domain/highlight/controller/HighlightController.java
  src/main/java/com/api/readinglog/domain/highlight/controller/dto/request/ModifyRequest.java
  src/main/java/com/api/readinglog/domain/highlight/controller/dto/request/WriteRequest.java
  src/main/java/com/api/readinglog/domain/highlight/controller/dto/response/HighlightResponse.java
  src/main/java/com/api/readinglog/domain/highlight/entity/Highlight.java
  src/main/java/com/api/readinglog/domain/highlight/repository/HighlightRepository.java
  src/main/java/com/api/readinglog/domain/highlight/service/HighlightService.java
  src/main/java/com/api/readinglog/domain/hightlight/repository/HighlightRepository.java
  src/main/java/com/api/readinglog/domain/member/controller/MemberController.java
  src/main/java/com/api/readinglog/domain/member/controller/dto/request/DeleteRequest.java
  src/main/java/com/api/readinglog/domain/member/controller/dto/request/JoinNicknameRequest.java
  src/main/java/com/api/readinglog/domain/member/controller/dto/request/LoginRequest.java
  src/main/java/com/api/readinglog/domain/member/controller/dto/request/UpdatePasswordRequest.java
  src/main/java/com/api/readinglog/domain/member/entity/Member.java
  src/main/java/com/api/readinglog/domain/member/service/MemberService.java
  src/main/java/com/api/readinglog/domain/record/controller/RecordController.java
  src/main/java/com/api/readinglog/domain/record/controller/dto/request/RecordModifyRequest.java
  src/main/java/com/api/readinglog/domain/record/controller/dto/request/RecordWriteRequest.java
  src/main/java/com/api/readinglog/domain/record/controller/dto/response/RecordResponse.java
  src/main/java/com/api/readinglog/domain/record/entity/Record.java
  src/main/java/com/api/readinglog/domain/record/repository/RecordRepository.java
  src/main/java/com/api/readinglog/domain/record/service/RecordService.java
  src/main/java/com/api/readinglog/domain/review/controller/ReviewController.java
  src/main/java/com/api/readinglog/domain/review/repository/ReviewRepository.java
  src/main/java/com/api/readinglog/domain/review/service/ReviewService.java
  src/main/java/com/api/readinglog/domain/summary/controller/SummaryController.java
  src/main/java/com/api/readinglog/domain/summary/service/SummaryService.java
  src/main/resources/data.sql
  src/main/resources/templates/authCode.html
  src/main/resources/templates/tempPassword.html
Labels: pull request, deploy

#82 Main 변경점 develop에 merge
  README.md
  src/main/java/com/api/readinglog/common/redis/config/RedisConfig.java
Labels: pull request, deploy, feature

#84 북로그 좋아요 기능 구현
  src/main/java/com/api/readinglog/common/cache/CacheInitializer.java
  src/main/java/com/api/readinglog/common/redis/service/RedisService.java
  src/main/java/com/api/readinglog/domain/book/entity/Book.java
  src/main/java/com/api/readinglog/domain/booklog/service/BookLogService.java
  src/main/java/com/api/readinglog/domain/like/service/LikeSummaryService.java
  src/main/java/com/api/readinglog/domain/member/controller/MemberController.java
  src/main/java/com/api/readinglog/domain/summary/controller/SummaryController.java
  src/main/java/com/api/readinglog/domain/summary/controller/dto/response/SummaryResponse.java
  src/main/java/com/api/readinglog/domain/summary/entity/Summary.java
Labels: pull request, feature

#87 CacheInitializer 오류 해결
  src/main/java/com/api/readinglog/common/cache/CacheInitializer.java
Labels: bug, pull request

#89 통계 기능 구현
  .gitignore
  build.gradle
  src/main/java/com/api/readinglog/common/querydsl/QuerydslConfig.java
  src/main/java/com/api/readinglog/domain/book/dto/BookCalendarResponse.java
  src/main/java/com/api/readinglog/domain/book/dto/BookCategoryResponse.java
  src/main/java/com/api/readinglog/domain/book/repository/BookRepository.java
  src/main/java/com/api/readinglog/domain/book/repository/CustomBookRepository.java
  src/main/java/com/api/readinglog/domain/book/repository/CustomBookRepositoryImpl.java
  src/main/java/com/api/readinglog/domain/stat/controller/StatController.java
  src/main/java/com/api/readinglog/domain/stat/controller/dto/StatResponse.java
  src/main/java/com/api/readinglog/domain/stat/service/StatService.java
  src/main/resources/application.yml
Labels: pull request, feature

#91 좋아요 테이블 추가
  src/main/java/com/api/readinglog/common/cache/CacheInitializer.java
  src/main/java/com/api/readinglog/domain/booklog/service/BookLogService.java
  src/main/java/com/api/readinglog/domain/likesummary/entity/LikeSummary.java
  src/main/java/com/api/readinglog/domain/likesummary/repository/LikeSummaryRepository.java
  src/main/java/com/api/readinglog/domain/likesummary/service/LikeSummaryService.java
  src/main/java/com/api/readinglog/domain/member/controller/MemberController.java
  src/main/java/com/api/readinglog/domain/summary/controller/SummaryController.java
Labels: pull request, feature

#94 책 검색 API 수정
  src/main/java/com/api/readinglog/domain/book/controller/BookController.java
  src/main/java/com/api/readinglog/domain/book/service/BookService.java
Labels: pull request, feature

#96 통계 기능 추가
  src/main/java/com/api/readinglog/domain/book/repository/CustomBookRepository.java
  src/main/java/com/api/readinglog/domain/book/repository/CustomBookRepositoryImpl.java
  src/main/java/com/api/readinglog/domain/likesummary/repository/CustomLikeSummaryRepository.java
  src/main/java/com/api/readinglog/domain/likesummary/repository/CustomLikeSummaryRepositoryImpl.java
  src/main/java/com/api/readinglog/domain/likesummary/repository/LikeSummaryRepository.java
  src/main/java/com/api/readinglog/domain/stat/service/StatService.java
  src/main/resources/data.sql
Labels: pull request, feature

#99 북로그 검색 기능 구현
  src/main/java/com/api/readinglog/domain/booklog/controller/BookLogController.java
  src/main/java/com/api/readinglog/domain/booklog/controller/dto/request/BookLogsSearchByBookTitleRequest.java
  src/main/java/com/api/readinglog/domain/booklog/controller/dto/request/BookLogsSearchByCategoryRequest.java
  src/main/java/com/api/readinglog/domain/booklog/service/BookLogService.java
  src/main/java/com/api/readinglog/domain/summary/controller/dto/response/MySummaryResponse.java
  src/main/java/com/api/readinglog/domain/summary/controller/dto/response/SummaryPageResponse.java
  src/main/java/com/api/readinglog/domain/summary/controller/dto/response/SummaryResponse.java
  src/main/java/com/api/readinglog/domain/summary/repository/CustomSummaryRepository.java
  src/main/java/com/api/readinglog/domain/summary/repository/CustomSummaryRepositoryImpl.java
  src/main/java/com/api/readinglog/domain/summary/repository/SummaryRepository.java
Labels: pull request, feature, refactor

#101 책 목록 조회 기능 구현
  src/main/java/com/api/readinglog/domain/book/controller/BookController.java
  src/main/java/com/api/readinglog/domain/book/dto/BookResponse.java
  src/main/java/com/api/readinglog/domain/book/dto/BookSearchApiResponse.java
  src/main/java/com/api/readinglog/domain/book/repository/CustomBookRepository.java
  src/main/java/com/api/readinglog/domain/book/repository/CustomBookRepositoryImpl.java
  src/main/java/com/api/readinglog/domain/book/service/BookService.java
Labels: pull request, feature

#102 04.11 MAIN MERGE
  src/main/java/com/api/readinglog/domain/book/controller/BookController.java
  src/main/java/com/api/readinglog/domain/book/dto/BookResponse.java
  src/main/java/com/api/readinglog/domain/book/dto/BookSearchApiResponse.java
  src/main/java/com/api/readinglog/domain/book/repository/CustomBookRepository.java
  src/main/java/com/api/readinglog/domain/book/repository/CustomBookRepositoryImpl.java
  src/main/java/com/api/readinglog/domain/book/service/BookService.java
  src/main/java/com/api/readinglog/domain/booklog/controller/BookLogController.java
  src/main/java/com/api/readinglog/domain/booklog/controller/dto/request/BookLogsSearchByBookTitleRequest.java
  src/main/java/com/api/readinglog/domain/booklog/controller/dto/request/BookLogsSearchByCategoryRequest.java
  src/main/java/com/api/readinglog/domain/booklog/service/BookLogService.java
  src/main/java/com/api/readinglog/domain/summary/controller/dto/response/MySummaryResponse.java
  src/main/java/com/api/readinglog/domain/summary/controller/dto/response/SummaryPageResponse.java
  src/main/java/com/api/readinglog/domain/summary/controller/dto/response/SummaryResponse.java
  src/main/java/com/api/readinglog/domain/summary/repository/CustomSummaryRepository.java
  src/main/java/com/api/readinglog/domain/summary/repository/CustomSummaryRepositoryImpl.java
  src/main/java/com/api/readinglog/domain/summary/repository/SummaryRepository.java
Labels: pull request, deploy

#104 스웨거 문서 정리
  src/main/java/com/api/readinglog/domain/book/controller/BookController.java
Labels: documentation, pull request

#105 04.11 MAIN MERGE
  src/main/java/com/api/readinglog/domain/book/controller/BookController.java
Labels: pull request

#107 회원 비밀번호 찾기 API 리팩토링
  src/main/java/com/api/readinglog/domain/email/service/EmailService.java
  src/main/java/com/api/readinglog/domain/member/controller/MemberController.java
  src/main/java/com/api/readinglog/domain/member/service/MemberService.java
Labels: pull request, refactor

#108 MAIN MERGE [이메일 로직 수정]
  src/main/java/com/api/readinglog/domain/email/service/EmailService.java
  src/main/java/com/api/readinglog/domain/member/controller/MemberController.java
  src/main/java/com/api/readinglog/domain/member/service/MemberService.java
Labels: pull request, refactor

#111 책 API 수정
  src/main/java/com/api/readinglog/common/aws/AmazonS3Service.java
  src/main/java/com/api/readinglog/domain/book/dto/BookDetailResponse.java
  src/main/java/com/api/readinglog/domain/book/service/BookService.java
Labels: pull request, feature

#112 책 API 수정 반영
  src/main/java/com/api/readinglog/common/aws/AmazonS3Service.java
  src/main/java/com/api/readinglog/domain/book/dto/BookDetailResponse.java
  src/main/java/com/api/readinglog/domain/book/service/BookService.java
Labels: pull request, deploy
